language: elixir
elixir: 
    - 1.10
addons: # ensure that Travis-CI provisions a DB for our test:
  postgresql: '9.5'
script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
